### ISSUE TITLE
[ Suggestion ] Integration with Minimal UI

### ISSUE THREAD

**Issue by MarceloCortezz** [ironmonk88/monks-scene-navigation#11]
I am using both modules (Minimal UI and Monk's Scene Navigation) and I can't live without, but it would be cool to have Minimal UI applied to Monk's Scene Navigation.

**Comment by ironmonk88** [comment]
I think this is better handled by Minimal UI.
Closing this ticket, but I suggested some changes for Minimal UI that should help integrate the two.
And it looks like its been mentioned with that module, so they're aware of it.
