### ISSUE TITLE
Add Icon Border to Improve Contrast and Compatibility

### ISSUE THREAD

**Issue by tjlanza** [ironmonk88/monks-scene-navigation#13]
In attempting to use this module alongside a UI skinning module (such as [Ernie's Modern Layout](https://github.com/ernieayala/ernies-modern-layout)) some things can appear in different places. Adding a thin, dark border to the icon would make it more visible against a wider variety of background colors.

![image](https://user-images.githubusercontent.com/21128724/116143193-d6006a00-a6a8-11eb-8f1f-2be99ca3dbd3.png)

**Comment by ironmonk88** [comment]
Text shadow has been added.
Available with the latest release.
