### ISSUE TITLE
Option to rearrange folders 

### ISSUE THREAD

**Issue by Avitale34** [ironmonk88/monks-scene-navigation#14]
Is it possible to allow the movements of folder's on the top bar? I can't seem to rearrange them.

**Comment by ironmonk88** [comment]
You can set them to be before the scenes or after the scenes.

Otherwise they should maintain the order that is set on the sidebar directory, changing the order there will change the order on the scene navigation.

**Comment by ironmonk88** [comment]
Closing this because I think it's a bit beyond the scope of this module, and Foundry has ways of ordering the Scenes that this module will respect.
