### ISSUE TITLE
[Request] Option to enable / disable changes to scene buttons on the canvas for GM

### ISSUE THREAD

**Issue by dmaneyapanda** [ironmonk88/monks-scene-navigation#17]
I like this module because it changes the default behavior for the Scene tab to be click to display a scene, rather than click to configure, along with the other enhancements to the Scene sidebar tab.

However, there are times when I wished that the default behavior for the canvas was not changed, because I don't have enough scenes marked for navigation to need a large folder structure displayed.  This request is to create an option to disable the canvas changes for the GM, similar to the "Show folders for players" option that already exists for the players.

**Comment by ironmonk88** [comment]
Option has been added in the latest version.
