### ISSUE TITLE
Possible Bad Link

### ISSUE THREAD

**Issue by VoltCruelerz** [ironmonk88/monks-scene-navigation#2]
![image](https://user-images.githubusercontent.com/4068550/107953974-daeac400-6f69-11eb-8050-992cea2a5cfe.png)

That link sends you to the module json, not the project.  I assume this is not intentional.  

Unless I'm misunderstanding how those links are generated, this looks like the right structure, such as what you have for token bar which does link correctly.

![image](https://user-images.githubusercontent.com/4068550/107954380-619fa100-6f6a-11eb-9f85-1987f324573f.png)

**Comment by ironmonk88** [comment]
Totally unintentional.
Should be fixed now, thank you!
