### ISSUE TITLE
Improvement - Settings option to disable special CSS

### ISSUE THREAD

**Issue by minakitty** [ironmonk88/monks-scene-navigation#21]
A player of mine was a bit distracted with the chance in UI that this module did on the coloring and border (I'm thinking related to #13 ), and he found that he was able to turn off just that one option with a tweak to one or two lines of CSS in browser (image attached)

We were wondering if, since it appears to be a very minor tweak, if it's something that could be added to module settings as a player togglable option?

![image](https://user-images.githubusercontent.com/5273418/127763568-48869bb1-92a1-4464-a180-5f6822137e61.png)

**Comment by ironmonk88** [comment]
So
![image](https://user-images.githubusercontent.com/75920956/127781017-858e0df5-4291-47e4-897b-643cb8a9d5c1.png)
But available on a per player basis?

**Comment by minakitty** [comment]
That sounds probably exactly like what we're looking for. After i filed this, I had another player who said they were interested

**Comment by ironmonk88** [comment]
Added to the latest release.
