### ISSUE TITLE
Scene do not show up when imported from Moulinette.

### ISSUE THREAD

**Issue by Cambridgeworks** [ironmonk88/monks-scene-navigation#26]
See title.
![Scene Issue](https://user-images.githubusercontent.com/90286611/141701635-7a2e8778-76e2-43d7-a5d2-09f4e92e84e4.png)

**Comment by ironmonk88** [comment]
I'm not sure what's wrong with the image?
Scenes won't show up if they havn't been set with Toggle Navigation.
And only High Hall has been set to navigable.

**Comment by ironmonk88** [comment]
Closing this as I'm not entirely sure what the issue is, and there's been no response.
