### ISSUE TITLE
Option to hide scene thumbnail images

### ISSUE THREAD

**Issue by epsilon7430** [ironmonk88/monks-scene-navigation#27]
As a GM user, I prefer scenes to be listed in the Scene tab without their thumbnails, so I can see more scenes listed at one time and organize them easier.  Listed scene titles should be left-aligned.  Thanks

**Comment by ironmonk88** [comment]
Added to the latest release

**Comment by epsilon7430** [comment]
Awesom, thank you!

Minor suggestion to help with feature discovery: change configuration item title from "Scene Directory Size" to "Scene Directory Size and Images".  Thanks
