### ISSUE TITLE
[REQUEST] Make "Hide Background" option apply to all connected clients

### ISSUE THREAD

**Issue by ianm32** [ironmonk88/monks-scene-navigation#29]
It would be helpful for ensuring the consistency of my players' experience if hiding the background of the nav bar could apply to all connected clients instead of just locally.

I usually don't make the scenes in navigation visible to my players, so in my specific case, the background mostly just creates an unsightly empty purple box across the top of the player view.

**Comment by ironmonk88** [comment]
This is a little out of the scope of Scene Navigation.
I'd recommend using a module like [Monk's Player Settings](https://foundryvtt.com/packages/monks-player-settings), or [Force Client Settings](https://foundryvtt.com/packages/force-client-settings) to update all your player's settings.
