### ISSUE TITLE
Feature Suggestion - quick way to set initial scene position

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-scene-navigation#3]
Is it possible to add an option to the dropdown of a Scene that will change the Initial Scene Position to the current camera position and zoom?

![image](https://user-images.githubusercontent.com/4083812/110007705-a590f500-7d23-11eb-8f9c-6764a1804850.png)

**Comment by ironmonk88** [comment]
Added to 1.0.8.  Will only show up with the currently active view.  As it doesn't make sense to set the view on non visible scenes.
