### ISSUE TITLE
Compatibility issue with Lockview?

### ISSUE THREAD

**Issue by Tatonker** [ironmonk88/monks-scene-navigation#31]
Hi,

I've noticed that with Lockview activated the scene navigation bar does not align properly with the canvas and is basically pushed off to the left when the side bar is minimized (see video attached). Not sure if there's a solution / or if this is known?

![image](https://user-images.githubusercontent.com/70360365/154899072-26eb1b92-1b4b-4f68-90bd-66049016de5d.png)

Regards,

Tatonker

**Comment by ironmonk88** [comment]
Is this still an issue?  I have Lockview installed but the Scene Navigation is behaving as it should be.

**Comment by ironmonk88** [comment]
Closing this as there's been no response and I think Lockview might have fixed it.

**Comment by Tatonker** [comment]
Hi, apologies I didn't even see that there was an initial response to my ticket and wasn't ignoring you intentionally. As of today 12/4/2022 I am still having exactly the same issue with only Monk's Scene Navigation and Lockview enabled.

Attaching images of an example scene where the navigation bar is pushed off the left edge of the screen as well as the settings for Lockview.

![image](https://user-images.githubusercontent.com/70360365/205521151-a1e82a67-b51e-4753-afaf-d2b7898f4937.png)
![image](https://user-images.githubusercontent.com/70360365/205521195-3e719ca3-2780-4fa3-948d-9419b64ed3da.png)
