### ISSUE TITLE
Option to set Scene Bar collapse behavior?

### ISSUE THREAD

**Issue by Tatonker** [ironmonk88/monks-scene-navigation#32]
Hi,

Would it be possible to get options to set the standard behavior of the Scene Navigation bar? For example, to start collapsed when when you navigate or activate a new scene, or to auto collapse on combat start? I often find when engaging in combat that the expanded Navigation Bar overlays on top of Token Action HUD, and scene navigation is not often a priority when engaging in combat.

Thanks,

Tatonker

**Comment by afalk** [comment]
Fantastic idea -- can I further suggest adding an option to SET the max # of 'columns' to better help with managing screen space side-to-side? I find the scene nav hides parts of the screen I need to be able to access ( active effects or levels for example) -- add this to the collapsible settings would be awesome :D

**Comment by ironmonk88** [comment]
The settings should be available in the latest version.

As for setting the size, I'd recommend the [Custom Css Module](https://foundryvtt.com/packages/custom-css).  That's the easiest way to add space on the side.
`#navigation { padding-right: 50px;}`
