### ISSUE TITLE
Double-click to activate scene does not work

### ISSUE THREAD

**Issue by dirusulixes** [ironmonk88/monks-scene-navigation#33]
fvtt 9.269
monks-scene-navigation 1.0.22
No other module enabled.

With the double-click to activate setting on nothing happens when double-clicking on a scene in the scene navigation bar or in scenes directory tab.

**Comment by dirusulixes** [comment]
Maybe I figured it out. I had the Modify Scene Bar setting disabled. With that enabled, double-clicking works for me. Having seen them as two independent options I thought I could have the latter without the former.

**Comment by ironmonk88** [comment]
Closing this as it should be fixed in the latest release
