### ISSUE TITLE
Removing background in navigation bar create issue with the display of the folder

### ISSUE THREAD

**Issue by davelacorneille** [ironmonk88/monks-scene-navigation#35]
If I remove the background of the navigation bar (from the setting), the "active" folder before too big and hide the scene below.

![image](https://user-images.githubusercontent.com/99104959/180918030-2408204d-6af3-4878-a6e2-f4e9b996b6f5.png)

**Comment by davelacorneille** [comment]
More info: The bug happen when you activate Minimal UI module.

**Comment by GambetTV** [comment]
I'm also experiencing this.

**Comment by ironmonk88** [comment]
This needs to be posted with Minimal UI.  Between the two of us, I think most of the overlapping styles issues have been handled by Minimal UI.
