### ISSUE TITLE
[BUG] Cannot Access Level 3 folders in the new update

### ISSUE THREAD

**Issue by danil0man** [ironmonk88/monks-scene-navigation#39]
**Describe the bug**
When I try to access level 3 folders in the bar, it doesn't let me. It just goes up back to the first level

**To Reproduce**
1. Open one of the folders
![image](https://user-images.githubusercontent.com/72052103/194850057-72ee3f4e-f408-4406-b142-0f904067ac39.png)

2. Click on the folder
![image](https://user-images.githubusercontent.com/72052103/194850123-fdc3010e-709b-4206-bb3b-ceb33950838c.png)

3. When I clock on the level 3 folder it returns to the level 1 folder. It don't go deeper than that.
As you can see I have a 3d level folder and inside I have images. The bar does not go deeper than 2
![image](https://user-images.githubusercontent.com/72052103/194850515-5e269b20-3c5e-4e85-9d2a-e33682bb3ce2.png)

**Expected behavior**
It was working before the update to go deeper into folders

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser Brave Chromium
 - Foundry Version 10.287
 - System Warhammer Fantasy Roleplay 4th Edition 
 - Module version 6.1.4
 - Are there any errors in the console 
![image](https://user-images.githubusercontent.com/72052103/194850811-6ddc960d-e3df-4eea-9067-c0213f344152.png)
But it seems to be unrelated to the folder going deeper
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
![image](https://user-images.githubusercontent.com/72052103/194851073-7b68c54a-f975-42c9-8f0e-77492756d014.png)
**Additional context**
It was working before the update today

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
