### ISSUE TITLE
Configurable navigation bar

### ISSUE THREAD

**Issue by ssveter1** [ironmonk88/monks-scene-navigation#41]
One of the things that is frustrating is not being able to organize the navigation bar. I cannot rearrange or drag the tabs.

Make the navigation bar tabs draggable to ba able to reaarange their order. See below, they are not in alphanumerical order.

![image](https://user-images.githubusercontent.com/10831302/200629506-8d281568-a502-40f1-b591-60764d26eae7.png)

**Comment by w1face** [comment]
Yes please!

**Comment by ironmonk88** [comment]
What system are you using?  I'm able to re-order the tabs.

**Comment by w1face** [comment]
Ah!  I think it stems from how we're used to re-ordering.  If you try and drag a scene to the *end* of the line (i.e. beyond the final one), it doesn't work.  Same as if we try and drag it *between* two other ones.

But dragging it ON to a different scene works.

**Comment by ironmonk88** [comment]
The best I can do is fix drag and drop onto the end.  Dragging in between scenes will put the scene at the end.

**Comment by ironmonk88** [comment]
Added to the latest release
