### ISSUE TITLE
Option to remote black box and use default text on scene thumbnails

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-scene-navigation#43]
**Is your feature request related to a problem? Please describe.**
Default scene thumbnails
![image](https://user-images.githubusercontent.com/84493092/202804566-eb781698-5666-43a6-a4f4-c44b18754ccc.png)

With Scene Navigation installed
![image](https://user-images.githubusercontent.com/84493092/202804622-99c08929-7e74-4864-ae38-5f24633af509.png)

It would be great to not have the larger font and black box. Thanks!

**Comment by ironmonk88** [comment]
Closing this as it should be fixed in the latest release
