### ISSUE TITLE
[BUG] Dragging Folders in Nav Bar

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-scene-navigation#44]
Dragging a folder in the nav bar doesn't rearrange the bar and errors.

![image](https://user-images.githubusercontent.com/99844555/204101044-c21662d3-da53-45f8-9241-7f8dd12d8a92.png)

https://user-images.githubusercontent.com/99844555/204100951-1b87ee22-4897-4130-bc50-6fd5a5021100.mp4

Foundry 10.290
Scene Nav 10.2

**Comment by ironmonk88** [comment]
Closing this as it should be fixed in the latest release
