### ISSUE TITLE
[BUG] Dragging Currently Active Scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-scene-navigation#45]
The currently active scene can only be dragged to the left to rearrange the nav bar; nothing happens when dragging it to the right. No errors.

https://user-images.githubusercontent.com/99844555/204101153-f3f41f9c-1420-4f50-a198-974e8f386727.mp4

Foundry 10.290
Scene Nav 10.2

**Comment by ironmonk88** [comment]
Closing this as it should be fixed in the latest release
