### ISSUE TITLE
[Feature Request] Back Button

### ISSUE THREAD

**Issue by SecretSquirrel77** [ironmonk88/monks-scene-navigation#46]
**Is your feature request related to a problem? Please describe.**
For those of us with quite a few scenes in a world, or those who may frequently change scenes to show a scene to players, a 'back button' like in a web browser, would be helpful. This would also be helpful when the GM accidentally activates the wrong scene.

**Describe the solution you'd like**
A 'back button' which probably only needs to store the previous scene visited.

**Additional context**
A highly useful shortcut to take mental load off a GM in the middle of a game. I can think of a time in nearly every session I run where I would use this at least once.

**Comment by Vlfberth** [comment]
@ironmonk88 could you please add an option to make this available to players as well?

I have a bunch of maps that they can navigate (as in world map -> kingdom maps -> city maps -> buildings) and it's easy enough to allow them to go to the next level of "zooming in" by adding tile triggers upon the kingdom/city/building names, but adding a "back" button requires me to arbitrarily choose somewhere blank on the map to place the trigger, it's... far from ideal.
When I saw this feature I thought my problems were solved, but sadly players can't see/use the button

pretty please? :D

**Comment by ironmonk88** [comment]
Added to the latest release

**Comment by Vlfberth** [comment]
Thank you!
