### ISSUE TITLE
[BUG] "Display Real Name" does not work if "Modify Scene Bar" is not checked

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-scene-navigation#47]
This is as of version 10.3, but this bug has existed prior to that as well.

I personally don't keep enough maps up per session to need the more complicated folder display of this module, but I love all the extra features you add beyond this. However, one of the most important ones for me is "Display Real Name", where the GM can see the real name of a scene, while the players see the Navigation Name. For whatever reason, having this option turned on does not work if "Modify Scene Bar" is turned off.

**Comment by GambetTV** [comment]
And to add to this, "Back Button" doesn't work if Modify Scene Bar is inactive, either. It occurs to me based on how much doesn't function when Modify Scene Bar is turned off that this might be intentional, but I really wish there was a way to get all these extra goodies without also being forced to use the clunkier folder structure which, maybe it's just because of the way I organize my scenes with folders within folders, but it's actually kind of a pain for me to navigate that way, which is why I like to leave it disabled.

**Comment by ironmonk88** [comment]
Added to the latest release
