### ISSUE TITLE
Ability to make the background of scene names white

### ISSUE THREAD

**Issue by peterprokurist** [ironmonk88/monks-scene-navigation#52]
I like the feature to add a dark background to the scene name.
Unfortunately, in some game systems (e.g. DSA/TDA The Dark Eye) the scene font is black.
The text is difficult to read with dark scenes. Your black background makes it a little better, but it would be even better with an optionally selectable white background :-)

Is it possible to add a feature in Monk's Scene Navigation that allows me to choose the background of the font to be white?
![image](https://user-images.githubusercontent.com/115837717/229202225-63ae88c6-5f16-47c9-9f85-dddb1d5872d0.png)

**Comment by ironmonk88** [comment]
Closing this as it should be fixed in the latest release
