### ISSUE TITLE
[BUG] V11 Failure, Can't wrap 'SceneDirectory.prototype._onClickDocumentName', target does not exist or could not be found.

### ISSUE THREAD

**Issue by QuestionQuest117** [ironmonk88/monks-scene-navigation#54]
**Describe the bug**
I'm not well versed enough to know the cause of the bug, other than Foundry says it is likely due to the module not being updated for V11 and that it only comes up when libwrapper is active as well. Monks-scene-navigation does appear to still be functioning as I still have the navigation bar, markers for where everyone is, and smaller scene panels, but I figured I'd report it anyway. monks-active-tile-triggers is spitting out the same error as well as monks-enhanced-journal (except monks-enhanced-journal has an additional error and isn't functioning).

**To Reproduce**
1. Update to V11 Foundry
2. Run D&D5e world
3. Activate monks-scene-navigation and libwrapper

**Expected behavior**
Error appears along top warning of functionality

**Screenshots**
![image](https://github.com/ironmonk88/monks-scene-navigation/assets/54755301/e0420419-0135-421a-a3ef-c30407190037)
![image](https://github.com/ironmonk88/monks-scene-navigation/assets/54755301/194458f4-8a93-43e6-adde-6ffa4bff1db7)

**Please complete as much of the following information as possible:**
 - Browser Native Foundry Application
 - Foundry Version 11
 - System D&D5e
 - Module version 10.3
 - Are there any errors in the console: Yes
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes, libwrapper

**Additional context**
LibWrapperPackageError: lib-wrapper. Error detected in module Monk's Scene Navigation. It is likely this module has not been updated for FVTT Version 11 Stable.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/ironmonk88/monks-scene-navigation
Report this issue here: https://github.com/ironmonk88/monks-scene-navigation/issues

== Technical Details:
Detected by libWrapper.
Package ID= monks-scene-navigation
Error= Can't wrap 'SceneDirectory.prototype._onClickDocumentName', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, monks-scene-navigation]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at Object.fn (monks-scene-navigation.js:439:24)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8529:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
onError @ foundry.js:753

**Comment by OberstK** [comment]
Error also appears with foundry v10 build 291
module version 11.01
system d&d 5e

**Comment by ironmonk88** [comment]
Closing this as it should be fixed in the latest release.
