### ISSUE TITLE
Enable Scene Tab for Players

### ISSUE THREAD

**Issue by Vogliadicone** [ironmonk88/monks-scene-navigation#55]
As a GM I prefer of reducing the number of UI elements of the main screen for my players and deactivate the scene navigation for them. But to give them the option to change scenes as well, it would be nice, if the scene tab would also be visible for players, so that they can use it to navigate between scenes (like through their journals or compendiums).

[DF scene enhancement](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-scene-enhance) has this feature. But since your scene navigation is superior and it's the only feature I use from DF scene enhancements, I thought I might ask you to integrate this into your module (so that I can delete the other module).

**Comment by ironmonk88** [comment]
Added to the latest release
