### ISSUE TITLE
[BUG] Player's Scene Directory

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-scene-navigation#63]
Players are unable to see scenes in the scene directory with this module setting enabled.

https://github.com/ironmonk88/monks-scene-navigation/assets/99844555/ae255fbf-5ac1-41aa-9f3a-fcac44863be5

Foundry 11.315
SN 11.04

**Comment by ironmonk88** [comment]
Unfortunately Foundry has completely locked out the ability to have this feature.
