### ISSUE TITLE
Set Camera Position does not appear for current non-activated scenes

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-scene-navigation#7]
If the current scene is non-activated (the target circle is not another scene) the option Set Camera Position will not appear in the dropdown menu. It should since the scene can be edited.

**Comment by ironmonk88** [comment]
I always get view and active reversed.  I thought I double-checked that... but apparently not.
Should be fixed in the next release.

**Comment by ironmonk88** [comment]
Should be fixed now, closing the ticket.
