### ISSUE TITLE
Opening different folder should close folders at same or lower level

### ISSUE THREAD

**Issue by Noshei** [ironmonk88/monks-scene-navigation#9]
If you open a folder, any other folders that are at the same level in the folder structure should automatically get closed.  This would make navigation so much easier and reduce the need to first close a folder before opening another one.  This would also remove the potential confusion of opening a folder and nothing changing on the display.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
I completely redesigned how the folder information was gather in the last release and this part was missed.
Thank you for catching it.
